### ISSUE TITLE
Handling for duplicate hamlet account ids

### ISSUE THREAD

**Issue by ken9ross** [hamlet-io/executor-bash#199] opened 2021-04-20 05:12 UTC
## Expected Behaviour
If there is a profile named the AWSid and one named the account id, the one named AWSid should have precedence

## Current Behaviour
When scanning for the profile to use within .aws/config, it checks first for the account id and, only if not found, then for the AWSid. There is no subsequent check whether this is related to the correct AWSid

## Possible Solution
Reverse the order so it checks for the unique AWSid first, only if not found, then for the (mostly unique) account id

## Context
Defend against reuse of hamlet account ids. Manual workaround is to always name profiles in .aws/config by their AWSid

**Comment by roleyfoley** [comment] 2021-06-12 04:26
On reviewing the credentials configuration in #222 it appears that the current order is right. Since each Id is evaluated after each other the most specific Id, PROVIDERID which should be the cloud providers Id is last in the list and will override the previous profiles. 

Combining that with the caller-identity check should resolve this as an issue

**Comment by roleyfoley** [comment] 2021-06-12 04:26
@ken9ross could you try and reproduce this once #222 has been merged and see if it fixes the issue

**Comment by ken9ross** [comment] 2021-06-21 05:07
@roleyfoley It does work, but it asks for both MFA codes when the wrong one has the matching name and the correct one has the AWSid

**Comment by roleyfoley** [comment] 2021-06-21 06:05
Have you got the example of where you had the issue? It sounds like that might be a misconfiguration of the aws profile.

**Comment by ken9ross** [comment] 2021-06-21 06:17
.aws/config has

[profile 946777400149]
description=dawrhelpdesk prod (GS hosted dawr07 946777400149)
source_profile = gs-jump
...

[profile dawr07]
description=Passport Scanner Production 688252938236 dawr07
source_profile = dawr-access
...

run under gs-gs/dawrhelpdesk

export ACCOUNT=dawr07
hamlet manage crypto -d -v -t 'encrypted_password' (I used the SLACK_TOKEN but I don't imagine it makes any difference)

**Closed** 2021-07-10 03:58 UTC
Labels: enhancement
